name: Jekyll site CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the site in the jekyll/builder container
      run: |
        # 1. 先安装依赖 (这一步会把 jekyll-admin 安装好)
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        jekyll/builder:latest /bin/bash -c "bundle install"

        # 2. 再进行构建
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
